//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/SolidLangParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SolidLangParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ISolidLangParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] SolidLangParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] SolidLangParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.annotations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotations([NotNull] SolidLangParser.AnnotationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.annotations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotations([NotNull] SolidLangParser.AnnotationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnnotation([NotNull] SolidLangParser.AnnotationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnnotation([NotNull] SolidLangParser.AnnotationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.namespace_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespace_decl_stmt([NotNull] SolidLangParser.Namespace_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.namespace_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespace_decl_stmt([NotNull] SolidLangParser.Namespace_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.namespace_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespace_path([NotNull] SolidLangParser.Namespace_pathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.namespace_path"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespace_path([NotNull] SolidLangParser.Namespace_pathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.namespace_prefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamespace_prefix([NotNull] SolidLangParser.Namespace_prefixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.namespace_prefix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamespace_prefix([NotNull] SolidLangParser.Namespace_prefixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.using_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUsing_decl_stmt([NotNull] SolidLangParser.Using_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.using_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUsing_decl_stmt([NotNull] SolidLangParser.Using_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.const_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConst_decl_stmt([NotNull] SolidLangParser.Const_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.const_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConst_decl_stmt([NotNull] SolidLangParser.Const_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.const_static_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConst_static_decl_stmt([NotNull] SolidLangParser.Const_static_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.const_static_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConst_static_decl_stmt([NotNull] SolidLangParser.Const_static_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_decl_stmt([NotNull] SolidLangParser.Struct_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_decl_stmt([NotNull] SolidLangParser.Struct_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_fields([NotNull] SolidLangParser.Struct_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_fields([NotNull] SolidLangParser.Struct_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_field([NotNull] SolidLangParser.Struct_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_field([NotNull] SolidLangParser.Struct_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.union_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion_decl_stmt([NotNull] SolidLangParser.Union_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.union_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion_decl_stmt([NotNull] SolidLangParser.Union_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.union_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion_fields([NotNull] SolidLangParser.Union_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.union_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion_fields([NotNull] SolidLangParser.Union_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.union_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnion_field([NotNull] SolidLangParser.Union_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.union_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnion_field([NotNull] SolidLangParser.Union_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.enum_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum_decl_stmt([NotNull] SolidLangParser.Enum_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.enum_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum_decl_stmt([NotNull] SolidLangParser.Enum_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.enum_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum_fields([NotNull] SolidLangParser.Enum_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.enum_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum_fields([NotNull] SolidLangParser.Enum_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.enum_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnum_field([NotNull] SolidLangParser.Enum_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.enum_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnum_field([NotNull] SolidLangParser.Enum_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.func_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_decl_stmt([NotNull] SolidLangParser.Func_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.func_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_decl_stmt([NotNull] SolidLangParser.Func_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.func_decl_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_decl_header([NotNull] SolidLangParser.Func_decl_headerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.func_decl_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_decl_header([NotNull] SolidLangParser.Func_decl_headerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.func_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_parameters([NotNull] SolidLangParser.Func_parametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.func_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_parameters([NotNull] SolidLangParser.Func_parametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.func_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_parameter([NotNull] SolidLangParser.Func_parameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.func_parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_parameter([NotNull] SolidLangParser.Func_parameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.interface_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterface_decl_stmt([NotNull] SolidLangParser.Interface_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.interface_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterface_decl_stmt([NotNull] SolidLangParser.Interface_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.interface_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterface_fields([NotNull] SolidLangParser.Interface_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.interface_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterface_fields([NotNull] SolidLangParser.Interface_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.generic_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_params([NotNull] SolidLangParser.Generic_paramsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.generic_params"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_params([NotNull] SolidLangParser.Generic_paramsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.generic_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGeneric_param([NotNull] SolidLangParser.Generic_paramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.generic_param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGeneric_param([NotNull] SolidLangParser.Generic_paramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.where_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhere_clauses([NotNull] SolidLangParser.Where_clausesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.where_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhere_clauses([NotNull] SolidLangParser.Where_clausesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhere_clause([NotNull] SolidLangParser.Where_clauseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.where_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhere_clause([NotNull] SolidLangParser.Where_clauseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] SolidLangParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] SolidLangParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.named_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamed_type([NotNull] SolidLangParser.Named_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.named_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamed_type([NotNull] SolidLangParser.Named_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.func_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_type([NotNull] SolidLangParser.Func_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.func_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_type([NotNull] SolidLangParser.Func_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.ref_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRef_type([NotNull] SolidLangParser.Ref_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.ref_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRef_type([NotNull] SolidLangParser.Ref_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.pointer_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointer_type([NotNull] SolidLangParser.Pointer_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.pointer_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointer_type([NotNull] SolidLangParser.Pointer_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.tuple_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple_type([NotNull] SolidLangParser.Tuple_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.tuple_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple_type([NotNull] SolidLangParser.Tuple_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_type([NotNull] SolidLangParser.Array_typeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.array_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_type([NotNull] SolidLangParser.Array_typeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] SolidLangParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] SolidLangParser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.empty_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty_stmt([NotNull] SolidLangParser.Empty_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.empty_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty_stmt([NotNull] SolidLangParser.Empty_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.body_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody_stmt([NotNull] SolidLangParser.Body_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.body_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody_stmt([NotNull] SolidLangParser.Body_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign_stmt([NotNull] SolidLangParser.Assign_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.assign_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign_stmt([NotNull] SolidLangParser.Assign_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.assign_pseudo_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign_pseudo_expr([NotNull] SolidLangParser.Assign_pseudo_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.assign_pseudo_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign_pseudo_expr([NotNull] SolidLangParser.Assign_pseudo_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.expr_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr_stmt([NotNull] SolidLangParser.Expr_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.expr_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr_stmt([NotNull] SolidLangParser.Expr_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.defer_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefer_stmt([NotNull] SolidLangParser.Defer_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.defer_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefer_stmt([NotNull] SolidLangParser.Defer_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf_stmt([NotNull] SolidLangParser.If_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf_stmt([NotNull] SolidLangParser.If_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile_stmt([NotNull] SolidLangParser.While_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile_stmt([NotNull] SolidLangParser.While_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_stmt([NotNull] SolidLangParser.For_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.for_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_stmt([NotNull] SolidLangParser.For_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.foreach_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeach_stmt([NotNull] SolidLangParser.Foreach_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.foreach_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeach_stmt([NotNull] SolidLangParser.Foreach_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.foreach_vars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForeach_vars([NotNull] SolidLangParser.Foreach_varsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.foreach_vars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForeach_vars([NotNull] SolidLangParser.Foreach_varsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.switch_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_stmt([NotNull] SolidLangParser.Switch_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.switch_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_stmt([NotNull] SolidLangParser.Switch_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.switch_cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_cases([NotNull] SolidLangParser.Switch_casesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.switch_cases"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_cases([NotNull] SolidLangParser.Switch_casesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.switch_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_case([NotNull] SolidLangParser.Switch_caseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.switch_case"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_case([NotNull] SolidLangParser.Switch_caseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.switch_labels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_labels([NotNull] SolidLangParser.Switch_labelsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.switch_labels"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_labels([NotNull] SolidLangParser.Switch_labelsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.switch_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitch_label([NotNull] SolidLangParser.Switch_labelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.switch_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitch_label([NotNull] SolidLangParser.Switch_labelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.break_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreak_stmt([NotNull] SolidLangParser.Break_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.break_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreak_stmt([NotNull] SolidLangParser.Break_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.continue_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinue_stmt([NotNull] SolidLangParser.Continue_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.continue_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinue_stmt([NotNull] SolidLangParser.Continue_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn_stmt([NotNull] SolidLangParser.Return_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.return_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn_stmt([NotNull] SolidLangParser.Return_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.var_decl_pseudo_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_decl_pseudo_expr([NotNull] SolidLangParser.Var_decl_pseudo_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.var_decl_pseudo_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_decl_pseudo_expr([NotNull] SolidLangParser.Var_decl_pseudo_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.var_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_decl_stmt([NotNull] SolidLangParser.Var_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.var_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_decl_stmt([NotNull] SolidLangParser.Var_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.static_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatic_decl_stmt([NotNull] SolidLangParser.Static_decl_stmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.static_decl_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatic_decl_stmt([NotNull] SolidLangParser.Static_decl_stmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] SolidLangParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] SolidLangParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.conditional_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditional_expr([NotNull] SolidLangParser.Conditional_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.conditional_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditional_expr([NotNull] SolidLangParser.Conditional_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.or_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOr_expr([NotNull] SolidLangParser.Or_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.or_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOr_expr([NotNull] SolidLangParser.Or_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnd_expr([NotNull] SolidLangParser.And_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnd_expr([NotNull] SolidLangParser.And_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.bit_or_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBit_or_expr([NotNull] SolidLangParser.Bit_or_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.bit_or_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBit_or_expr([NotNull] SolidLangParser.Bit_or_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.bit_xor_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBit_xor_expr([NotNull] SolidLangParser.Bit_xor_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.bit_xor_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBit_xor_expr([NotNull] SolidLangParser.Bit_xor_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.bit_and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBit_and_expr([NotNull] SolidLangParser.Bit_and_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.bit_and_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBit_and_expr([NotNull] SolidLangParser.Bit_and_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.eq_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEq_expr([NotNull] SolidLangParser.Eq_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.eq_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEq_expr([NotNull] SolidLangParser.Eq_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.cmp_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCmp_expr([NotNull] SolidLangParser.Cmp_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.cmp_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCmp_expr([NotNull] SolidLangParser.Cmp_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.shift_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterShift_expr([NotNull] SolidLangParser.Shift_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.shift_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitShift_expr([NotNull] SolidLangParser.Shift_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.add_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdd_expr([NotNull] SolidLangParser.Add_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.add_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdd_expr([NotNull] SolidLangParser.Add_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.mul_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMul_expr([NotNull] SolidLangParser.Mul_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.mul_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMul_expr([NotNull] SolidLangParser.Mul_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnary_expr([NotNull] SolidLangParser.Unary_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.unary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnary_expr([NotNull] SolidLangParser.Unary_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.postfix_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix_expr([NotNull] SolidLangParser.Postfix_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.postfix_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix_expr([NotNull] SolidLangParser.Postfix_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.postfix_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPostfix_suffix([NotNull] SolidLangParser.Postfix_suffixContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.postfix_suffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPostfix_suffix([NotNull] SolidLangParser.Postfix_suffixContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary_expr([NotNull] SolidLangParser.Primary_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.primary_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary_expr([NotNull] SolidLangParser.Primary_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.meta_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeta_expr([NotNull] SolidLangParser.Meta_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.meta_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeta_expr([NotNull] SolidLangParser.Meta_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.meta_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeta_args([NotNull] SolidLangParser.Meta_argsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.meta_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeta_args([NotNull] SolidLangParser.Meta_argsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.meta_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMeta_arg([NotNull] SolidLangParser.Meta_argContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.meta_arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMeta_arg([NotNull] SolidLangParser.Meta_argContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.tuple_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple_literal([NotNull] SolidLangParser.Tuple_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.tuple_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple_literal([NotNull] SolidLangParser.Tuple_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.tuple_elements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTuple_elements([NotNull] SolidLangParser.Tuple_elementsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.tuple_elements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTuple_elements([NotNull] SolidLangParser.Tuple_elementsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_literal([NotNull] SolidLangParser.Struct_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_literal([NotNull] SolidLangParser.Struct_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_literal_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_literal_fields([NotNull] SolidLangParser.Struct_literal_fieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_literal_fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_literal_fields([NotNull] SolidLangParser.Struct_literal_fieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_literal_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_literal_field([NotNull] SolidLangParser.Struct_literal_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_literal_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_literal_field([NotNull] SolidLangParser.Struct_literal_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.array_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray_literal([NotNull] SolidLangParser.Array_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.array_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray_literal([NotNull] SolidLangParser.Array_literalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteral([NotNull] SolidLangParser.LiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteral([NotNull] SolidLangParser.LiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.call_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCall_args([NotNull] SolidLangParser.Call_argsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.call_args"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCall_args([NotNull] SolidLangParser.Call_argsContext context);
}
