//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from grammar/SolidLangParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISolidLangParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class SolidLangParserBaseListener : ISolidLangParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] SolidLangParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] SolidLangParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.annotations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotations([NotNull] SolidLangParser.AnnotationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.annotations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotations([NotNull] SolidLangParser.AnnotationsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnnotation([NotNull] SolidLangParser.AnnotationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.annotation"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnnotation([NotNull] SolidLangParser.AnnotationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.namespace_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_decl_stmt([NotNull] SolidLangParser.Namespace_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.namespace_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_decl_stmt([NotNull] SolidLangParser.Namespace_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.namespace_path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_path([NotNull] SolidLangParser.Namespace_pathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.namespace_path"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_path([NotNull] SolidLangParser.Namespace_pathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.namespace_prefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_prefix([NotNull] SolidLangParser.Namespace_prefixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.namespace_prefix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_prefix([NotNull] SolidLangParser.Namespace_prefixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.using_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsing_decl_stmt([NotNull] SolidLangParser.Using_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.using_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsing_decl_stmt([NotNull] SolidLangParser.Using_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.const_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConst_decl_stmt([NotNull] SolidLangParser.Const_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.const_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConst_decl_stmt([NotNull] SolidLangParser.Const_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.const_static_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConst_static_decl_stmt([NotNull] SolidLangParser.Const_static_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.const_static_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConst_static_decl_stmt([NotNull] SolidLangParser.Const_static_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_decl_stmt([NotNull] SolidLangParser.Struct_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_decl_stmt([NotNull] SolidLangParser.Struct_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_fields([NotNull] SolidLangParser.Struct_fieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_fields([NotNull] SolidLangParser.Struct_fieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_field([NotNull] SolidLangParser.Struct_fieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_field([NotNull] SolidLangParser.Struct_fieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.union_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnion_decl_stmt([NotNull] SolidLangParser.Union_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.union_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnion_decl_stmt([NotNull] SolidLangParser.Union_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.union_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnion_fields([NotNull] SolidLangParser.Union_fieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.union_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnion_fields([NotNull] SolidLangParser.Union_fieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.union_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnion_field([NotNull] SolidLangParser.Union_fieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.union_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnion_field([NotNull] SolidLangParser.Union_fieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.enum_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_decl_stmt([NotNull] SolidLangParser.Enum_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.enum_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_decl_stmt([NotNull] SolidLangParser.Enum_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.enum_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_fields([NotNull] SolidLangParser.Enum_fieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.enum_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_fields([NotNull] SolidLangParser.Enum_fieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.enum_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_field([NotNull] SolidLangParser.Enum_fieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.enum_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_field([NotNull] SolidLangParser.Enum_fieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.func_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_decl_stmt([NotNull] SolidLangParser.Func_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.func_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_decl_stmt([NotNull] SolidLangParser.Func_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.func_decl_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_decl_header([NotNull] SolidLangParser.Func_decl_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.func_decl_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_decl_header([NotNull] SolidLangParser.Func_decl_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.func_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_parameters([NotNull] SolidLangParser.Func_parametersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.func_parameters"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_parameters([NotNull] SolidLangParser.Func_parametersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.func_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_parameter([NotNull] SolidLangParser.Func_parameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.func_parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_parameter([NotNull] SolidLangParser.Func_parameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.interface_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterface_decl_stmt([NotNull] SolidLangParser.Interface_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.interface_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterface_decl_stmt([NotNull] SolidLangParser.Interface_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.interface_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterface_fields([NotNull] SolidLangParser.Interface_fieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.interface_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterface_fields([NotNull] SolidLangParser.Interface_fieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.generic_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_params([NotNull] SolidLangParser.Generic_paramsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.generic_params"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_params([NotNull] SolidLangParser.Generic_paramsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.generic_param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneric_param([NotNull] SolidLangParser.Generic_paramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.generic_param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneric_param([NotNull] SolidLangParser.Generic_paramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.where_clauses"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhere_clauses([NotNull] SolidLangParser.Where_clausesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.where_clauses"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhere_clauses([NotNull] SolidLangParser.Where_clausesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.where_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhere_clause([NotNull] SolidLangParser.Where_clauseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.where_clause"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhere_clause([NotNull] SolidLangParser.Where_clauseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] SolidLangParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] SolidLangParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.named_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamed_type([NotNull] SolidLangParser.Named_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.named_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamed_type([NotNull] SolidLangParser.Named_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.func_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_type([NotNull] SolidLangParser.Func_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.func_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_type([NotNull] SolidLangParser.Func_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.ref_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRef_type([NotNull] SolidLangParser.Ref_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.ref_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRef_type([NotNull] SolidLangParser.Ref_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.pointer_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPointer_type([NotNull] SolidLangParser.Pointer_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.pointer_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPointer_type([NotNull] SolidLangParser.Pointer_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.tuple_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTuple_type([NotNull] SolidLangParser.Tuple_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.tuple_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTuple_type([NotNull] SolidLangParser.Tuple_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_type([NotNull] SolidLangParser.Array_typeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.array_type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_type([NotNull] SolidLangParser.Array_typeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] SolidLangParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] SolidLangParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.empty_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmpty_stmt([NotNull] SolidLangParser.Empty_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.empty_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmpty_stmt([NotNull] SolidLangParser.Empty_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.body_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody_stmt([NotNull] SolidLangParser.Body_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.body_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody_stmt([NotNull] SolidLangParser.Body_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.assign_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign_stmt([NotNull] SolidLangParser.Assign_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.assign_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign_stmt([NotNull] SolidLangParser.Assign_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.assign_pseudo_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign_pseudo_expr([NotNull] SolidLangParser.Assign_pseudo_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.assign_pseudo_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign_pseudo_expr([NotNull] SolidLangParser.Assign_pseudo_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.expr_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr_stmt([NotNull] SolidLangParser.Expr_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.expr_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr_stmt([NotNull] SolidLangParser.Expr_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.defer_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefer_stmt([NotNull] SolidLangParser.Defer_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.defer_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefer_stmt([NotNull] SolidLangParser.Defer_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_stmt([NotNull] SolidLangParser.If_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_stmt([NotNull] SolidLangParser.If_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.while_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_stmt([NotNull] SolidLangParser.While_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.while_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_stmt([NotNull] SolidLangParser.While_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.for_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_stmt([NotNull] SolidLangParser.For_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.for_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_stmt([NotNull] SolidLangParser.For_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.foreach_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeach_stmt([NotNull] SolidLangParser.Foreach_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.foreach_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeach_stmt([NotNull] SolidLangParser.Foreach_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.foreach_vars"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForeach_vars([NotNull] SolidLangParser.Foreach_varsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.foreach_vars"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForeach_vars([NotNull] SolidLangParser.Foreach_varsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.switch_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_stmt([NotNull] SolidLangParser.Switch_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.switch_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_stmt([NotNull] SolidLangParser.Switch_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.switch_cases"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_cases([NotNull] SolidLangParser.Switch_casesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.switch_cases"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_cases([NotNull] SolidLangParser.Switch_casesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.switch_case"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_case([NotNull] SolidLangParser.Switch_caseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.switch_case"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_case([NotNull] SolidLangParser.Switch_caseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.switch_labels"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_labels([NotNull] SolidLangParser.Switch_labelsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.switch_labels"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_labels([NotNull] SolidLangParser.Switch_labelsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.switch_label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_label([NotNull] SolidLangParser.Switch_labelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.switch_label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_label([NotNull] SolidLangParser.Switch_labelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.break_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreak_stmt([NotNull] SolidLangParser.Break_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.break_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreak_stmt([NotNull] SolidLangParser.Break_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.continue_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinue_stmt([NotNull] SolidLangParser.Continue_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.continue_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinue_stmt([NotNull] SolidLangParser.Continue_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.return_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturn_stmt([NotNull] SolidLangParser.Return_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.return_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturn_stmt([NotNull] SolidLangParser.Return_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.var_decl_pseudo_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_decl_pseudo_expr([NotNull] SolidLangParser.Var_decl_pseudo_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.var_decl_pseudo_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_decl_pseudo_expr([NotNull] SolidLangParser.Var_decl_pseudo_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.var_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_decl_stmt([NotNull] SolidLangParser.Var_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.var_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_decl_stmt([NotNull] SolidLangParser.Var_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.static_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatic_decl_stmt([NotNull] SolidLangParser.Static_decl_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.static_decl_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatic_decl_stmt([NotNull] SolidLangParser.Static_decl_stmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] SolidLangParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] SolidLangParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.conditional_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditional_expr([NotNull] SolidLangParser.Conditional_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.conditional_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditional_expr([NotNull] SolidLangParser.Conditional_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOr_expr([NotNull] SolidLangParser.Or_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOr_expr([NotNull] SolidLangParser.Or_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnd_expr([NotNull] SolidLangParser.And_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnd_expr([NotNull] SolidLangParser.And_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.bit_or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBit_or_expr([NotNull] SolidLangParser.Bit_or_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.bit_or_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBit_or_expr([NotNull] SolidLangParser.Bit_or_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.bit_xor_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBit_xor_expr([NotNull] SolidLangParser.Bit_xor_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.bit_xor_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBit_xor_expr([NotNull] SolidLangParser.Bit_xor_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.bit_and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBit_and_expr([NotNull] SolidLangParser.Bit_and_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.bit_and_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBit_and_expr([NotNull] SolidLangParser.Bit_and_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.eq_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEq_expr([NotNull] SolidLangParser.Eq_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.eq_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEq_expr([NotNull] SolidLangParser.Eq_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.cmp_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCmp_expr([NotNull] SolidLangParser.Cmp_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.cmp_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCmp_expr([NotNull] SolidLangParser.Cmp_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.shift_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterShift_expr([NotNull] SolidLangParser.Shift_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.shift_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitShift_expr([NotNull] SolidLangParser.Shift_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.add_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdd_expr([NotNull] SolidLangParser.Add_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.add_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdd_expr([NotNull] SolidLangParser.Add_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.mul_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMul_expr([NotNull] SolidLangParser.Mul_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.mul_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMul_expr([NotNull] SolidLangParser.Mul_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.unary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnary_expr([NotNull] SolidLangParser.Unary_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.unary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnary_expr([NotNull] SolidLangParser.Unary_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.postfix_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix_expr([NotNull] SolidLangParser.Postfix_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.postfix_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix_expr([NotNull] SolidLangParser.Postfix_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.postfix_suffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostfix_suffix([NotNull] SolidLangParser.Postfix_suffixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.postfix_suffix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostfix_suffix([NotNull] SolidLangParser.Postfix_suffixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimary_expr([NotNull] SolidLangParser.Primary_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.primary_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimary_expr([NotNull] SolidLangParser.Primary_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.meta_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeta_expr([NotNull] SolidLangParser.Meta_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.meta_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeta_expr([NotNull] SolidLangParser.Meta_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.meta_args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeta_args([NotNull] SolidLangParser.Meta_argsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.meta_args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeta_args([NotNull] SolidLangParser.Meta_argsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.meta_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMeta_arg([NotNull] SolidLangParser.Meta_argContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.meta_arg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMeta_arg([NotNull] SolidLangParser.Meta_argContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.tuple_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTuple_literal([NotNull] SolidLangParser.Tuple_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.tuple_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTuple_literal([NotNull] SolidLangParser.Tuple_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.tuple_elements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTuple_elements([NotNull] SolidLangParser.Tuple_elementsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.tuple_elements"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTuple_elements([NotNull] SolidLangParser.Tuple_elementsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_literal([NotNull] SolidLangParser.Struct_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_literal([NotNull] SolidLangParser.Struct_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_literal_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_literal_fields([NotNull] SolidLangParser.Struct_literal_fieldsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_literal_fields"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_literal_fields([NotNull] SolidLangParser.Struct_literal_fieldsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.struct_literal_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_literal_field([NotNull] SolidLangParser.Struct_literal_fieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.struct_literal_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_literal_field([NotNull] SolidLangParser.Struct_literal_fieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.array_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray_literal([NotNull] SolidLangParser.Array_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.array_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray_literal([NotNull] SolidLangParser.Array_literalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] SolidLangParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] SolidLangParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SolidLangParser.call_args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCall_args([NotNull] SolidLangParser.Call_argsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SolidLangParser.call_args"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCall_args([NotNull] SolidLangParser.Call_argsContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
